# Generated by Django 4.2.1 on 2023-05-15 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0006_contact_us"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact_us",
            name="message",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
