# Generated by Django 4.2.1 on 2023-05-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0009_order_paid_order_payment_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="contry",
            new_name="country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="additional_info",
        ),
    ]
